pilotos_cor = {
    '0 - Caca Bueno': 'orange',
    '5 - Denis Navarro': 'seashell',
    '4 - Julio Campos': 'white',
    '7 - Joao Paulo de Oliveira': 'seashell',
    '8 - Rafael Suzuki': 'darkgreen',
    '9 - Arthur Gama': 'seashell',
    '10 - Ricardo Zonta': 'crimson',
    '11 - Gaetano Di Mauro': 'greenyellow',
    '12 - Lucas Foresti': 'purple',
    '18 - Allam Khodair': 'blue',
    '19 - Felipe Massa': 'darkgreen',
    '21 - Thiago Camilo': 'yellow',
    '73 - Enzo Elias': 'lightblue',
    '29 - Daniel Serra': 'blue',
    '30 - Cesar Ramos': 'yellow',
    '33 - Nelson Piquet Jr': 'grey',
    '38 - Zezinho Mugiatti': 'orange',
    '44- Bruno Baptista': 'crimson',
    '51 - Atila Abreu': 'lightblue',
    '81 - Arthur Leist': 'white',
    '83 - Gabriel Casagrande': 'purple',
    '85 - Guilherme Salas': 'orange',
    '88 - Felipe Fraga': 'greenyellow',
    '90 - Ricardo Mauricio': 'orange',
    '95 - Lucas Kohl': 'orange',
    '101 - Gianluca Petecof': 'seashell',
    '111 - Rubens Barrichello': 'seashell',
    '121 - Felipe Baptista': 'navy',
    '27 - Renan Guerra': 'dodgerblue'
}

pilotos_cor_amattheis = {
    '0 - Caca Bueno': 'silver',
    '6 - Helio Castroneves': 'green',
    '5 - Denis Navarro': 'silver',
    '4 - Julio Campos': 'silver',
    '7 - Joao Paulo de Oliveira': 'silver',
    '8 - Rafael Suzuki': 'silver',
    '9 - Arthur Gama': 'silver',
    '10 - Ricardo Zonta': 'silver',
    '11 - Gaetano Di Mauro': 'silver',
    '12 - Lucas Foresti': 'dimgrey',
    '18 - Allam Khodair': 'silver',
    '19 - Felipe Massa': 'silver',
    '21 - Thiago Camilo': 'red',
    '73 - Enzo Elias': 'silver',
    '29 - Daniel Serra': 'silver',
    '30 - Cesar Ramos': 'yellow',
    '33 - Nelson Piquet Jr': 'silver',
    '38 - Zezinho Mugiatti': 'silver',
    '44- Bruno Baptista': 'silver',
    '51 - Atila Abreu': 'silver',
    '81 - Arthur Leist': 'silver',
    '83 - Gabriel Casagrande': 'purple',
    '85 - Guilherme Salas': 'silver',
    '88 - Felipe Fraga': 'silver',
    '90 - Ricardo Mauricio': 'silver',
    '95 - Lucas Kohl': 'silver',
    '101 - Gianluca Petecof': 'silver',
    '111 - Rubens Barrichello': 'silver',
    '121 - Felipe Baptista': 'silver',
    '27 - Renan Guerra': 'dodgerblue'
}

equipes_cor_old = {
    'Ipiranga Racing': 'yellow',
    'Eurofarma Rc': 'greenyellow',
    'Cavaleiro Sports': 'darkgreen',
    'Full Time/Cavaleiro': 'crimson',
    'Car Racing Ktf': 'orange',
    'Rcm Motorsport': 'red',
    'Amattheis Vogel': 'grey',
    'Tmg Racing': 'darkgreen',
    'Ft Gazoo Racing': 'navy',
    'Scuderia Chiarelli': 'seashell',
    'Rtr Sport Team': 'crimson',
    'Blau Motorsport': 'blue',
    'Crown Racing': 'black',
    'Car Racing Sterling': 'white',
    'Scuderia Bandeiras Sports': 'silver',
    'Scuderia Bandeiras': 'lightblue'
}

equipes_cor = {
    'MERCADO LIVRE RACING TEAM': 'yellow',
    'EUROFARMA RC': 'greenyellow',
    'VALDA-CAVALEIRO SPORTS': 'darkgreen',
    'FULL TIME GAZOO RACING': 'crimson',
    'CAR RACING': 'orange',
    'TEAM RC': 'red',
    'VOGEL MOTORSPORT': 'grey',
    'TMG RACING': 'darkgreen',
    'RTR SG28 TEAM': 'navy',
    'SCUDERIA CHIARELLI': 'seashell',
    'RTR SG28': 'crimson',
    'BLAU MOTORSPORT': 'blue',
    'CROWN RACING': 'black',
    'STERLING RACING': 'white',
    'SCUDERIA BANDEIRAS SPORTS': 'silver',
    'SCUDERIA BANDEIRAS': 'lightblue'
}

equipes_pilotos_old = {
    '0 - Caca Bueno': 'Scuderia Chiarelli',
    '4 - Julio Campos': 'Crown Racing',
    '5 - Denis Navarro': 'Full Time/Cavaleiro',
    '6 - Helio Castro Neves': 'Rtr Sport Team',
    '7 - Joao Paulo De Oliveira': 'Ft Gazoo Racing',
    '8 - Rafael Suzuki': 'Tmg Racing',
    '9 - Arthur Gama': 'Ft Gazoo Racing',
    '10 - Ricardo Zonta': 'Rcm Motorsport',
    '11 - Gaetano Di Mauro': 'Eurofarma Rc',
    '12 - Lucas Foresti': 'Amattheis Vogel',
    '18 - Allam Khodair': 'Blau Motorsport',
    '19 - Felipe Massa': 'Tmg Racing',
    '21 - Thiago Camilo': 'Ipiranga Racing',
    '73 - Enzo Elias': 'Scuderia Bandeiras',
    '29 - Daniel Serra': 'Blau Motorsport',
    '30 - Cesar Ramos': 'Ipiranga Racing',
    '33 - Nelson Piquet Jr': 'Scuderia Bandeiras Sports',
    '38 - Zezinho Mugiatti': 'Car Racing Sterling',
    '38 - Zezinho Muggiati': 'Car Racing Sterling',
    '44 - Bruno Baptista': 'Rcm Motorsport',
    '51 - Atila Abreu': 'Scuderia Bandeiras',
    '81 - Arthur Leist': 'Crown Racing',
    '83 - Gabriel Casagrande': 'Amattheis Vogel',
    '85 - Guilherme Salas': 'Cavaleiro Sports',
    '88 - Felipe Fraga': 'Eurofarma Rc',
    '90 - Ricardo Mauricio': 'Cavaleiro Sports',
    '95 - Lucas Kohl': 'Scuderia Chiarelli',
    '101 - Gianluca Petecof': 'Car Racing Ktf',
    '111 - Rubens Barrichello': 'Full Time/Cavaleiro',
    '121 - Felipe Baptista': 'Car Racing Ktf',
    '301 - Rafael Reis': 'Car Racing Sterling',
    '444 - Vicente Orige': 'Scuderia Bandeiras Sports',
    '27 - Renan Guerra': 'Amattheis Vogel'
}

modelo_cor = {
    'Toyota': 'red',
    'Mitsubishi': 'grey',
    'Chevrolet': 'blue'
}

piloto_modelo_old = {
    '88 - Felipe Fraga': 'Mitsubishi',
    '11 - Gaetano Di Mauro': 'Mitsubishi',
    '85 - Guilherme Salas': 'Chevrolet',
    '121 - Felipe Baptista': 'Mitsubishi',
    '12 - Lucas Foresti': 'Chevrolet',
    '90 - Ricardo Mauricio': 'Chevrolet',
    '5 - Denis Navarro': 'Toyota',
    '44 - Bruno Baptista': 'Mitsubishi',
    '8 - Rafael Suzuki': 'Chevrolet',
    '111 - Rubens Barrichello': 'Toyota',
    '30 - Cesar Ramos': 'Toyota',
    '10 - Ricardo Zonta': 'Mitsubishi',
    '7 - Joao Paulo De Oliveira': 'Toyota',
    '95 - Lucas Kohl': 'Chevrolet',
    '6 - Helio Castro Neves': 'Chevrolet',
    '6 - Helio Castroneves': 'Chevrolet',
    '51 - Atila Abreu': 'Chevrolet',
    '81 - Arthur Leist': 'Toyota',
    '38 - Zezinho Muggiati': 'Toyota',
    '444 - Vicente Orige': 'Mitsubishi',
    '18 - Allam Khodair': 'Mitsubishi',
    '73 - Enzo Elias': 'Chevrolet',
    '21 - Thiago Camilo': 'Toyota',
    '29 - Daniel Serra': 'Mitsubishi',
    '101 - Gianluca Petecof': 'Mitsubishi',
    '301 - Rafael Reis': 'Toyota',
    '83 - Gabriel Casagrande': 'Chevrolet',
    '19 - Felipe Massa': 'Chevrolet',
    '0 - Caca Bueno': 'Chevrolet',
    '9 - Arthur Gama': 'Toyota',
    '33 - Nelson Piquet Jr': 'Mitsubishi',
    '4 - Julio Campos': 'Toyota',
    '27 - Renan Guerra': 'Chevrolet'
}

piloto_modelo = {
    '11 - Gaetano Di Mauro': 'Mitsubishi',
    '1 - Felipe Fraga': 'Mitsubishi',
    '4 - Julio Campos': 'Chevrolet',
    '83 - Gabriel Casagrande': 'Chevrolet',
    '29 - Daniel Serra': 'Mitsubishi',
    '7 - Sergio Sette Camara': 'Mitsubishi',
    '293 - Leonardo Reis': 'Toyota',
    '8 - Rafael Suzuki': 'Chevrolet',
    '111 - Rubens Barrichello': 'Mitsubishi',
    '38 - Zezinho Muggiati': 'Mitsubishi',
    '21 - Thiago Camilo': 'Toyota',
    '73 - Enzo Elias': 'Toyota',
    '81 - Arthur Leist': 'Toyota',
    '12 - Lucas Foresti': 'Chevrolet',
    '30 - Cesar Ramos': 'Toyota',
    '85 - Guilherme Salas': 'Chevrolet',
    '19 - Felipe Massa': 'Chevrolet',
    '444 - Vicente Orige': 'Mitsubishi',
    '33 - Nelson Piquet Jr': 'Mitsubishi',
    '0 - Caca Bueno': 'Chevrolet',
    '18 - Allam Khodair': 'Mitsubishi',
    '301 - Rafael Reis': 'Toyota',
    '51 - Atila Abreu': 'Chevrolet',
    '80 - Alfredinho Ibiapina': 'Toyota',
    '27 - Renan Guerra': 'Toyota',
    '6 - Helio Castroneves': 'Chevrolet',
    '10 - Ricardo Zonta': 'Toyota',
    '22 - Andre Moraes Jr': 'Chevrolet',
    '95 - Lucas Kohl': 'Toyota',
    '90 - Ricardo Mauricio': 'Chevrolet',
    '24 - Felipe Bartz': 'Mitsubishi',
    '97 - Bruna Tomaselli': 'Toyota',
    '121 - Felipe Baptista': 'Mitsubishi',
}

equipes_pilotos = {
    '11 - Gaetano Di Mauro': 'EUROFARMA RC',
    '1 - Felipe Fraga': 'EUROFARMA RC',
    '4 - Julio Campos': 'TMG RACING',
    '83 - Gabriel Casagrande': 'VOGEL MOTORSPORT',
    '29 - Daniel Serra': 'BLAU MOTORSPORT',
    '7 - Sergio Sette Camara': 'TEAM RC',
    '293 - Leonardo Reis': 'CAR RACING',
    '8 - Rafael Suzuki': 'SCUDERIA BANDEIRAS',
    '111 - Rubens Barrichello': 'SCUDERIA BANDEIRAS SPORTS',
    '38 - Zezinho Muggiati': 'TEAM RC',
    '21 - Thiago Camilo': 'MERCADO LIVRE RACING TEAM',
    '73 - Enzo Elias': 'AMATTHEIS/TMG',
    '81 - Arthur Leist': 'CROWN RACING',
    '12 - Lucas Foresti': 'VOGEL MOTORSPORT',
    '30 - Cesar Ramos': 'MERCADO LIVRE RACING TEAM',
    '85 - Guilherme Salas': 'VALDA-CAVALEIRO SPORTS',
    '19 - Felipe Massa': 'TMG RACING',
    '444 - Vicente Orige': 'STERLING RACING',
    '33 - Nelson Piquet Jr': 'SCUDERIA BANDEIRAS',
    '0 - Caca Bueno': 'SCUDERIA CHIARELLI',
    '18 - Allam Khodair': 'BLAU MOTORSPORT',
    '301 - Rafael Reis': 'CAR RACING',
    '51 - Atila Abreu': 'SCUDERIA BANDEIRAS SPORT',
    '80 - Alfredinho Ibiapina': 'FULL TIME GAZOO RACING',
    '27 - Renan Guerra': 'AMATTHEIS/TMG',
    '6 - Helio Castroneves': 'MERCADO LIVRE RACING',
    '10 - Ricardo Zonta': 'FULL TIME GAZOO RACING',
    '22 - Andre Moraes Jr': 'SCUDERIA CHIARELLI',
    '95 - Lucas Kohl': 'CROWN RACING',
    '90 - Ricardo Mauricio': 'VALDA-CAVALEIRO SPORTS',
    '24 - Felipe Bartz': 'RTR SG28 TEAM',
    '97 - Bruna Tomaselli': 'RTR SG28',
    '121 - Felipe Baptista': 'STERLING RACING',
}
