pilotos_cor = {
    '0 - Caca Bueno': 'orange',
    '5 - Denis Navarro': 'seashell',
    '4 - Julio Campos': 'black',
    '8 - Rafael Suzuki': 'darkgreen',
    '10 - Ricardo Zonta': 'crimson',
    '11 - Gaetano Di Mauro': 'grey',
    '12 - Lucas Foresti': 'lightblue',
    '18 - Allam Khodair': 'blue',
    '19 - Felipe Massa': 'darkgreen',
    '21 - Thiago Camilo': 'yellow',
    '73 - Enzo Elias': 'navy',
    '29 - Daniel Serra': 'greenyellow',
    '30 - Cesar Ramos': 'yellow',
    '33 - Nelson Piquet Jr': 'grey',
    '38 - Zezinho Mugiatti': 'orange',
    '44- Bruno Baptista': 'crimson',
    '51 - Atila Abreu': 'black',
    '81 - Arthur Leist': 'seashell',
    '83 - Gabriel Casagrande': 'lightblue',
    '85 - Guilherme Salas': 'orange',
    '88 - Felipe Fraga': 'blue',
    '90 - Ricardo Mauricio': 'greenyellow',
    '91 - Eduardo Barrichello': 'seashell',
    '95 - Lucas Kohl': 'silver',
    '101 - Gianluca Petecof': 'seashell',
    '111 - Rubens Barrichello': 'seashell',
    '121 - Felipe Baptista': 'navy'
}

equipes_cor = {
    'Ipiranga Racing': 'yellow',
    'Eurofarma Rc': 'greenyellow',
    'Cavaleiro Sports': 'darkgreen',
    'Full Time/Cavaleiro': 'crimson',
    'Car Racing Ktf': 'orange',
    'Rcm Motorsport': 'red',
    'Amattheis Vogel': 'grey',
    'Tmg Racing': 'darkgreen',
    'Ft Gazoo Racing': 'navy',
    'Scuderia Chiarelli': 'seashell',
    'Rtr Sport Team': 'crimson',
    'Blau Motorsport': 'blue',
    'Crown Racing': 'black',
    'Car Racing Sterling': 'white',
    'Scuderia Bandeiras Sports': 'silver',
    'Scuderia Bandeiras': 'lightblue'
}

equipes_pilotos = {
    '0 - Caca Bueno': 'Scuderia Chiarelli',
    '4 - Julio Campos': 'Crown Racing',
    '5 - Denis Navarro': 'Full Time/Cavaleiro',
    '6 - Helio Castro Neves': 'Rtr Sport Team',
    '7 - Joao Paulo De Oliveira': 'Ft Gazoo Racing',
    '8 - Rafael Suzuki': 'Tmg Racing',
    '9 - Arthur Gama': 'Ft Gazoo Racing',
    '10 - Ricardo Zonta': 'Rcm Motorsport',
    '11 - Gaetano Di Mauro': 'Eurofarma Rc',
    '12 - Lucas Foresti': 'Amattheis Vogel',
    '18 - Allam Khodair': 'Blau Motorsport',
    '19 - Felipe Massa': 'Tmg Racing',
    '21 - Thiago Camilo': 'Ipiranga Racing',
    '73 - Enzo Elias': 'Scuderia Bandeiras',
    '29 - Daniel Serra': 'Blau Motorsport',
    '30 - Cesar Ramos': 'Ipiranga Racing',
    '33 - Nelson Piquet Jr': 'Scuderia Bandeiras Sports',
    '38 - Zezinho Mugiatti': 'Car Racing Sterling',
    '38 - Zezinho Muggiati': 'Car Racing Sterling',
    '44 - Bruno Baptista': 'Rcm Motorsport',
    '51 - Atila Abreu': 'Scuderia Bandeiras',
    '81 - Arthur Leist': 'Crown Racing',
    '83 - Gabriel Casagrande': 'Amattheis Vogel',
    '85 - Guilherme Salas': 'Cavaleiro Sports',
    '88 - Felipe Fraga': 'Eurofarma Rc',
    '90 - Ricardo Mauricio': 'Cavaleiro Sports',
    '95 - Lucas Kohl': 'Scuderia Chiarelli',
    '101 - Gianluca Petecof': 'Car Racing Ktf',
    '111 - Rubens Barrichello': 'Full Time/Cavaleiro',
    '121 - Felipe Baptista': 'Car Racing Ktf',
    '301 - Rafael Reis': 'Car Racing Sterling',
    '444 - Vicente Orige': 'Scuderia Bandeiras Sports'
}

modelo_cor = {
    'Toyota': 'grey',
    'Mitsubishi': 'red',
    'Chevrolet': 'orange'
}

piloto_modelo = {
    '88 - Felipe Fraga': 'Mitsubishi',
    '11 - Gaetano Di Mauro': 'Mitsubishi',
    '85 - Guilherme Salas': 'Chevrolet',
    '121 - Felipe Baptista': 'Mitsubishi',
    '12 - Lucas Foresti': 'Chevrolet',
    '90 - Ricardo Mauricio': 'Chevrolet',
    '5 - Denis Navarro': 'Toyota',
    '44 - Bruno Baptista': 'Mitsubishi',
    '8 - Rafael Suzuki': 'Chevrolet',
    '111 - Rubens Barrichello': 'Toyota',
    '30 - Cesar Ramos': 'Toyota',
    '10 - Ricardo Zonta': 'Mitsubishi',
    '7 - Joao Paulo De Oliveira': 'Toyota',
    '95 - Lucas Kohl': 'Chevrolet',
    '6 - Helio Castro Neves': 'Chevrolet',
    '51 - Atila Abreu': 'Chevrolet',
    '81 - Arthur Leis': 'Toyota',
    '38 - Zezinho Mugiatti': 'Toyota',
    '444 - Vicente Orige': 'Mitsubishi',
    '18 - Allam Khodair': 'Mitsubishi',
    '73 - Enzo Elias': 'Chevrolet',
    '21 - Thiago Camilo': 'Toyota',
    '29 - Daniel Serra': 'Mitsubishi',
    '101 - Gianluca Petecof': 'Mitsubishi',
    '301 - Rafael Reis': 'Toyota',
    '83 - Gabriel Casagrande': 'Chevrolet',
    '19 - Felipe Massa': 'Chevrolet',
    '0 - Caca Bueno': 'Chevrolet',
    '9 - Arthur Gama': 'Toyota',
    '33 - Nelson Piquet Jr': 'Mitsubishi',
    '4 - Julio Campos': 'Toyota'
}
